ninetyninecats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:create, :new]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

ninetyninecats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <header>
    <ul>
        <li>
          <%= link_to 'All Cats', cats_url %>
        </li>
      <% if current_user %>
        <li><%= current_user.user_name  %></li>
        <li>
          <form id="logout" action="<%= session_url %>" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <button type="submit">Logout</button>
          </form>
          <%#= button_to "Logout", session_url, method: :delete %>
        </li>
      <% else %>
        <li>
          <form id="sign_up" action="<%= new_user_url %>" method="GET">
            <button type="submit">Sign Up!</button>
          </form>
        </li>
        <li>
          <form id="login" action="<%= new_session_url %>" method="GET">
            <input type="submit" value="Login!">
          </form>
        </li>
      <% end%>
    </ul>

    <%= render 'shared/errors' %>
  </header>
  

    <%= yield %>
  </body>
</html>